-- Create profiles table
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  avatar_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Create learning_decks table
CREATE TABLE IF NOT EXISTS public.learning_decks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  ai_response_json JSONB,
  progress_percentage INTEGER DEFAULT 0 NOT NULL,
  is_public BOOLEAN DEFAULT false NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Create flashcard_decks table
CREATE TABLE IF NOT EXISTS public.flashcard_decks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  learning_deck_id BIGINT REFERENCES public.learning_decks(id) ON DELETE CASCADE NOT NULL,
  milestone_title TEXT NOT NULL,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Create flashcards table
CREATE TABLE IF NOT EXISTS public.flashcards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  flashcard_deck_id BIGINT REFERENCES public.flashcard_decks(id) ON DELETE CASCADE NOT NULL,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  difficulty TEXT CHECK (difficulty IN ('easy', 'medium', 'hard')) DEFAULT 'medium' NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Create milestone_progress table
CREATE TABLE IF NOT EXISTS public.milestone_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  learning_deck_id BIGINT REFERENCES public.learning_decks(id) ON DELETE CASCADE NOT NULL,
  milestone_index INTEGER NOT NULL,
  is_completed BOOLEAN DEFAULT false NOT NULL,
  completed_at TIMESTAMP WITH TIME ZONE,
  UNIQUE(user_id, learning_deck_id, milestone_index)
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_learning_decks_user_id ON public.learning_decks(user_id);
CREATE INDEX IF NOT EXISTS idx_learning_decks_is_public ON public.learning_decks(is_public);
CREATE INDEX IF NOT EXISTS idx_flashcard_decks_learning_deck_id ON public.flashcard_decks(learning_deck_id);
CREATE INDEX IF NOT EXISTS idx_flashcard_decks_user_id ON public.flashcard_decks(user_id);
CREATE INDEX IF NOT EXISTS idx_flashcards_flashcard_deck_id ON public.flashcards(flashcard_deck_id);
CREATE INDEX IF NOT EXISTS idx_milestone_progress_user_id ON public.milestone_progress(user_id);
CREATE INDEX IF NOT EXISTS idx_milestone_progress_learning_deck_id ON public.milestone_progress(learning_deck_id);

-- Create updated_at trigger function
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Drop existing triggers if they exist
DROP TRIGGER IF EXISTS handle_profiles_updated_at ON public.profiles;
DROP TRIGGER IF EXISTS handle_learning_decks_updated_at ON public.learning_decks;

-- Create triggers for updated_at
CREATE TRIGGER handle_profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER handle_learning_decks_updated_at
  BEFORE UPDATE ON public.learning_decks
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- Create Row Level Security (RLS) policies
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.learning_decks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.flashcard_decks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.flashcards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.milestone_progress ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can view own learning decks" ON public.learning_decks;
DROP POLICY IF EXISTS "Users can view public learning decks" ON public.learning_decks;
DROP POLICY IF EXISTS "Users can insert own learning decks" ON public.learning_decks;
DROP POLICY IF EXISTS "Users can update own learning decks" ON public.learning_decks;
DROP POLICY IF EXISTS "Users can delete own learning decks" ON public.learning_decks;
DROP POLICY IF EXISTS "Users can view own flashcard decks" ON public.flashcard_decks;
DROP POLICY IF EXISTS "Users can insert own flashcard decks" ON public.flashcard_decks;
DROP POLICY IF EXISTS "Users can update own flashcard decks" ON public.flashcard_decks;
DROP POLICY IF EXISTS "Users can delete own flashcard decks" ON public.flashcard_decks;
DROP POLICY IF EXISTS "Users can view own flashcards" ON public.flashcards;
DROP POLICY IF EXISTS "Users can insert own flashcards" ON public.flashcards;
DROP POLICY IF EXISTS "Users can update own flashcards" ON public.flashcards;
DROP POLICY IF EXISTS "Users can delete own flashcards" ON public.flashcards;
DROP POLICY IF EXISTS "Users can view own milestone progress" ON public.milestone_progress;
DROP POLICY IF EXISTS "Users can insert own milestone progress" ON public.milestone_progress;
DROP POLICY IF EXISTS "Users can update own milestone progress" ON public.milestone_progress;
DROP POLICY IF EXISTS "Users can delete own milestone progress" ON public.milestone_progress;

-- Profiles policies
CREATE POLICY "Users can view own profile"
  ON public.profiles FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Users can update own profile"
  ON public.profiles FOR UPDATE
  USING (auth.uid() = id);

CREATE POLICY "Users can insert own profile"
  ON public.profiles FOR INSERT
  WITH CHECK (auth.uid() = id);

-- Learning decks policies
CREATE POLICY "Users can view own learning decks"
  ON public.learning_decks FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can view public learning decks"
  ON public.learning_decks FOR SELECT
  USING (is_public = true);

CREATE POLICY "Users can insert own learning decks"
  ON public.learning_decks FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own learning decks"
  ON public.learning_decks FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own learning decks"
  ON public.learning_decks FOR DELETE
  USING (auth.uid() = user_id);

-- Flashcard decks policies
CREATE POLICY "Users can view own flashcard decks"
  ON public.flashcard_decks FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own flashcard decks"
  ON public.flashcard_decks FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own flashcard decks"
  ON public.flashcard_decks FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own flashcard decks"
  ON public.flashcard_decks FOR DELETE
  USING (auth.uid() = user_id);

-- Flashcards policies
CREATE POLICY "Users can view own flashcards"
  ON public.flashcards FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.flashcard_decks
      WHERE flashcard_decks.id = flashcards.flashcard_deck_id
      AND flashcard_decks.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can insert own flashcards"
  ON public.flashcards FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.flashcard_decks
      WHERE flashcard_decks.id = flashcards.flashcard_deck_id
      AND flashcard_decks.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can update own flashcards"
  ON public.flashcards FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.flashcard_decks
      WHERE flashcard_decks.id = flashcards.flashcard_deck_id
      AND flashcard_decks.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can delete own flashcards"
  ON public.flashcards FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.flashcard_decks
      WHERE flashcard_decks.id = flashcards.flashcard_deck_id
      AND flashcard_decks.user_id = auth.uid()
    )
  );

-- Milestone progress policies
CREATE POLICY "Users can view own milestone progress"
  ON public.milestone_progress FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own milestone progress"
  ON public.milestone_progress FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own milestone progress"
  ON public.milestone_progress FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own milestone progress"
  ON public.milestone_progress FOR DELETE
  USING (auth.uid() = user_id);
